### ISSUE TITLE
not be able to load the channel

### ISSUE THREAD

**Issue by sshweta7** [shihchinlin/vue-teams#5]
not be able to load the channel using Username: vue-teams@shihchinlin.onmicrosoft.com
Password: NTT5ySrZaMKvfFgh

**Comment by shihchinlin** [comment]
OK, I had recovered the same password for the same trial account

**Comment by bwwelle** [comment]
Hello.  I opened a different incident in regards to the code being updated, but was wondering if you could do the same as you did you above, again.  Thanks.
